// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using poi.Data;

namespace poi.Migrations
{
    [DbContext(typeof(POIContext))]
    [Migration("20220328061352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("poi.Models.POI", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Deleted");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("PoiType");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("TripId");

                    b.HasKey("Id");

                    b.ToTable("POIs");
                });
#pragma warning restore 612, 618
        }
    }
}
